name: Deploy to FTP Server

on:
  push:
    branches:
      - main # Sadece "main" branch'e push yapıldığında çalışacak

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Depoyu klonla
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. FTP sunucusuna bağlan ve dosyaları yükle
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./out # Yüklemek istediğin dizin (ör. build çıktısı)
        server-dir: ${{ secrets.FTP_PATH }}
